<?php

define('HTTP_BAD_REQUEST', 400);
define('HTTP_UNAUTHORIZED', 401);
define('HTTP_FORBIDDEN', 403);
define('HTTP_NOT_FOUND', 404);
define('HTTP_METHOD_NOT_ALLOWED', 405);
define('HTTP_INTERNAL_SERVER_ERROR', 500);

define('ID_COMMENT_STATUS_ACTIF', 1);
define('ID_COMMENT_STATUS_REFUSE', 2);
define('ID_COMMENT_STATUS_NON_TRAITE', 3);
